// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGCU24PUrp3i4xTRbqxgqeldlWUnSLW58',
    appId: '1:855849533096:web:a7d6c3e419e12db5894c9d',
    messagingSenderId: '855849533096',
    projectId: 'shopping-b2a85',
    authDomain: 'shopping-b2a85.firebaseapp.com',
    storageBucket: 'shopping-b2a85.appspot.com',
    measurementId: 'G-9G9WGKB7QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCySTMBTb2Zd_Zrwg875_F6LebvcRK4d_I',
    appId: '1:855849533096:android:40df32e7b8be3d1e894c9d',
    messagingSenderId: '855849533096',
    projectId: 'shopping-b2a85',
    storageBucket: 'shopping-b2a85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxl2zitQrDIroWr9AGdrkmoyUWHL0Phhg',
    appId: '1:855849533096:ios:2cb99c4a4c277e07894c9d',
    messagingSenderId: '855849533096',
    projectId: 'shopping-b2a85',
    storageBucket: 'shopping-b2a85.appspot.com',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxl2zitQrDIroWr9AGdrkmoyUWHL0Phhg',
    appId: '1:855849533096:ios:be9b257285d281a7894c9d',
    messagingSenderId: '855849533096',
    projectId: 'shopping-b2a85',
    storageBucket: 'shopping-b2a85.appspot.com',
    iosBundleId: 'com.example.shopping.RunnerTests',
  );
}
